"""initial anime model

Revision ID: b366de7a638c
Revises: 
Create Date: 2026-02-03 13:47:21.093228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b366de7a638c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_english', sa.String(), nullable=True),
    sa.Column('title_japanese', sa.String(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AIRING', 'FINISHED', 'UPCOMING', name='animestatus'), nullable=True),
    sa.Column('season', sa.Enum('WINTER', 'SUMMER', 'SPRING', 'FALL', name='animeseason'), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime')
    # ### end Alembic commands ###
